Update add new script and property

diff --git a/.github/workflows/update_for_azure_currencyexchangeservice.yml b/.github/workflows/update_for_azure_currencyexchangeservice.yml
--- a/.github/workflows/update_for_azure_currencyexchangeservice.yml
+++ b/.github/workflows/update_for_azure_currencyexchangeservice.yml
@@ -24,8 +24,14 @@ jobs:
       - name: Grant execute permission for gradlew
         run: chmod +x ./gradlew
 
-      - name: Build with Gradle Wrapper
-        run: ./gradlew clean build
+      - name: Clean build folder with Gradle
+        run: ./gradlew clean
+
+      - name: Run test using gradlew
+        run: ./gradlew test
+
+      - name: Build jar with Gradle Wrapper
+        run: ./gradlew jar
 
       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v4
@@ -65,25 +71,36 @@ jobs:
         with:
           app-name: 'currencyexchangeservice'
           slot-name: 'Production'
-          package: ./CurrencyExchangeService-0.0.2-SNAPSHOT.jar
+          package: ./CurrencyExchangeService-0.0.2-SNAPSHOT-plain.jar
           publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BA44D8CC83114D9D9C5B98F711512549 }}
-    
+
       - name: Save Deployment URL
         run: echo "APP_URL=${{ steps.deploy-to-webapp.outputs.webapp-url }}" >> $GITHUB_ENV
-        
+
   check-success:
     runs-on: ubuntu-latest
     needs: deploy
     steps:
-      - name: Wait 10 minutes for environment stabilization
-        run: sleep 600
-    
-      - name: Check App Availability
+      - name: Check App Availability with retry logic
         run: |
-          response=$(curl -o /dev/null -s -w "%{http_code}\n" ${{ env.APP_URL }}/api/currency?date=1980-01-01)
-          if [[ "$response" == "200" || "$response" == "203" || "$response" == "204" ]]; then
-            echo "Success: Service is up and running. Response status: $response"
-          else
-            echo "Fail: Service responded with status: $response"
-            exit 1
-          fi
+          url="${{ env.APP_URL }}/api/currency?date=1980-01-01"
+          attempts=0
+          max_attempts=5
+          delay=240
+
+          while [[ $attempts -lt $max_attempts ]]; do
+            response=$(curl -o /dev/null -s -w "%{http_code}\n" "$url")
+            if [[ "$response" == "200" || "$response" == "203" || "$response" == "204" ]]; then
+              echo "Success: Service is up and running. Response status: $response"
+              exit 0
+            else
+              echo "Attempt $((attempts + 1)) failed with status: $response"
+              ((attempts++))
+              echo "Waiting $delay seconds before retrying..."
+              sleep $delay
+              delay=$((delay / 2))  # Decrease delay for next retry
+            fi
+          done
+          
+          echo "Fail: Service responded with unacceptable status after $max_attempts attempts."
+          exit 1
