Update update_for_azure_currencyexchangeservice.yml

diff --git a/.github/workflows/update_for_azure_currencyexchangeservice.yml b/.github/workflows/update_for_azure_currencyexchangeservice.yml
--- a/.github/workflows/update_for_azure_currencyexchangeservice.yml
+++ b/.github/workflows/update_for_azure_currencyexchangeservice.yml
@@ -9,7 +9,6 @@ on:
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
     permissions:
       contents: write
@@ -33,6 +32,25 @@ jobs:
         with:
           name: java-app
           path: build/libs/*.jar
+
+  test:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - uses: actions/checkout@v4
+      - name: Set up JDK 17
+        uses: actions/setup-java@v4
+        with:
+          java-version: '17'
+          distribution: 'temurin'
+      
+      - name: Download artifact from build job
+        uses: actions/download-artifact@v4
+        with:
+          name: java-app
+
+      - name: Run Tests
+        run: java -jar build/libs/*.jar --test
 
   deploy:
     runs-on: ubuntu-latest
@@ -60,6 +78,17 @@ jobs:
     
       - name: Save Deployment URL
         run: echo "APP_URL=${{ steps.deploy-to-webapp.outputs.webapp-url }}" >> $GITHUB_ENV
-
-      - name: Display App URL
-        run: echo "App Service Application URL:$APP_URL"
+        
+  check-success:
+    runs-on: ubuntu-latest
+    needs: deploy
+    steps:
+      - name: Check App Availability
+        run: |
+          response=$(curl -o /dev/null -s -w "%{http_code}\n" ${{ env.APP_URL }}/api/currency?date=1980-01-01)
+          if [[ "$response" == "200" || "$response" == "203" || "$response" == "204" ]]; then
+            echo "Success: Service is up and running. Response status: $response"
+          else
+            echo "Fail: Service responded with status: $response"
+            exit 1
+          fi
